# Generated by Django 6.0.4 on 2026-04-07 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('client', models.CharField(blank=True, max_length=200, verbose_name='Клиент')),
                ('client_type', models.CharField(choices=[('port', 'Порт'), ('factory', 'Завод'), ('terminal', 'Терминал'), ('logistics', 'Логистический центр'), ('other', 'Другое')], max_length=20, verbose_name='Тип клиента')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('location', models.CharField(max_length=200, verbose_name='Локация')),
                ('task', models.TextField(verbose_name='Задача клиента')),
                ('solution', models.TextField(verbose_name='Наше решение')),
                ('result', models.TextField(verbose_name='Результат')),
                ('track_length_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Длина пути (км)')),
                ('switches_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Стрелочных переводов')),
                ('duration_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='Продолжительность (мес.)')),
                ('budget_display', models.CharField(blank=True, help_text='Например: от 150 млн тг', max_length=100, verbose_name='Бюджет (отображение)')),
                ('cover_image', models.ImageField(upload_to='projects/covers/', verbose_name='Обложка')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta Description')),
                ('is_featured', models.BooleanField(default=False, verbose_name='На главной')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-year', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/', verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, max_length=300, verbose_name='Alt текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Фото проекта',
                'verbose_name_plural': 'Фото проекта',
                'ordering': ['order'],
            },
        ),
    ]
