# Generated by Django 6.0.4 on 2026-04-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='full_description_en',
            field=models.TextField(blank=True, verbose_name='Полное описание (EN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_en',
            field=models.TextField(blank=True, max_length=300, verbose_name='Краткое описание (EN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название (EN)'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название (EN)'),
        ),
    ]
