# Generated by Django 6.0.4 on 2026-04-24 19:00

import django.db.models.deletion
import parler.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_service_full_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='full_description_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='short_description_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='name_en',
        ),
        migrations.AlterField(
            model_name='servicecategorytranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='services.servicecategory'),
        ),
        migrations.AlterField(
            model_name='servicetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='services.service'),
        ),
    ]
