# Generated by Django 6.0.4 on 2026-04-07 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория техники',
                'verbose_name_plural': 'Категории техники',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('purpose', models.TextField(verbose_name='Назначение')),
                ('application', models.TextField(blank=True, verbose_name='Где применяется')),
                ('specifications', models.JSONField(default=dict, help_text='{"Грузоподъемность": "25т"}', verbose_name='Технические характеристики')),
                ('image', models.ImageField(blank=True, upload_to='equipment/', verbose_name='Фото')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='equipment.equipmentcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Техника',
                'verbose_name_plural': 'Техника',
                'ordering': ['order'],
            },
        ),
    ]
