# Generated by Django 6.0.4 on 2026-04-24 19:00

import django.db.models.deletion
import parler.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_remove_equipment_application_remove_equipment_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='application_en',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='purpose_en',
        ),
        migrations.RemoveField(
            model_name='equipmentcategory',
            name='name_en',
        ),
        migrations.AlterField(
            model_name='equipmentcategorytranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='equipment.equipmentcategory'),
        ),
        migrations.AlterField(
            model_name='equipmenttranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='equipment.equipment'),
        ),
    ]
