# Generated by Django 6.0.4 on 2026-04-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects_count', models.PositiveIntegerField(default=0, verbose_name='Проектов выполнено')),
                ('track_km', models.PositiveIntegerField(default=0, verbose_name='Км пути уложено')),
                ('years_on_market', models.PositiveIntegerField(default=0, verbose_name='Лет на рынке')),
                ('employees_count', models.PositiveIntegerField(default=0, verbose_name='Сотрудников')),
            ],
            options={
                'verbose_name': 'Показатели компании',
                'verbose_name_plural': 'Показатели компании',
            },
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Компания')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработана')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': 'FAQ вопрос',
                'verbose_name_plural': 'FAQ вопросы',
                'ordering': ['order'],
            },
        ),
    ]
