# Generated by Django 6.0.4 on 2026-04-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqitem',
            name='answer_en',
            field=models.TextField(blank=True, verbose_name='Ответ (EN)'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='question_en',
            field=models.CharField(blank=True, max_length=500, verbose_name='Вопрос (EN)'),
        ),
    ]
