# Generated by Django 6.0.4 on 2026-04-24 19:00

import django.db.models.deletion
import parler.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_faqitem_answer_remove_faqitem_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqitem',
            name='answer_en',
        ),
        migrations.RemoveField(
            model_name='faqitem',
            name='question_en',
        ),
        migrations.AlterField(
            model_name='faqitemtranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.faqitem'),
        ),
    ]
