# Generated by Django 6.0.4 on 2026-04-07 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория статей',
                'verbose_name_plural': 'Категории статей',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('excerpt', models.TextField(max_length=350, verbose_name='Анонс')),
                ('content', models.TextField(verbose_name='Содержание (HTML)')),
                ('cover_image', models.ImageField(blank=True, upload_to='articles/', verbose_name='Обложка')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Автор')),
                ('published_at', models.DateField(verbose_name='Дата публикации')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta Description')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Главная')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.articlecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-published_at'],
            },
        ),
    ]
