# Generated by Django 6.0.4 on 2026-04-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_en',
            field=models.TextField(blank=True, verbose_name='Содержание (HTML) (EN)'),
        ),
        migrations.AddField(
            model_name='article',
            name='excerpt_en',
            field=models.TextField(blank=True, max_length=350, verbose_name='Анонс (EN)'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(blank=True, max_length=250, verbose_name='Заголовок (EN)'),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название (EN)'),
        ),
    ]
